### ISSUE TITLE
BUG: Min calculation

### ISSUE THREAD

**Issue by cloud-tribal** [vue-bulma/slider#3]
Hey don't know how to do pull request

PROBLEM: When you put minimum, the highlighted part of the slider does not follow the slider button.

SOLUTION: 
Line 56, replace:

`return this.realValue / this.max * 100 + '%'`

with
`return (this.realValue - this.min) / (this.max - this.min) * 100 + '%'`

**Comment by luventa** [comment]
Thanks! Fixed. And I added some logic to avoid other issue.
